// SAMPLE / DEMO DATA.
//
// Illustrative only. These are NOT any carrier's real trucks, rates, shippers
// or freight. The fleet is modeled on a Western New York bulk carrier whose
// trucks run road salt outbound from the Genesee Valley and come back empty;
// the loads are plausible regional backhauls with made-up pay. Everything is
// tagged `source: { kind: "demo" }` and the app labels it as sample data.
//
// Dates are fixed to the week of 28 September 2026 (Eastern time) so the demo
// is deterministic.

import type { Load, Place, Truck } from "./types";

export const DEMO_TENANT_ID = "demo-wny-bulk";
export const DEMO_TENANT_LABEL =
  "Sample fleet — Western NY bulk carrier (illustrative)";

const P = (name: string, lat: number, lon: number): Place => ({ name, lat, lon });

/** Known places for CSV import and the demo. Coordinates are city centres. */
export const DEMO_PLACES = {
  mountMorris: P("Mount Morris, NY", 42.7256, -77.8739),
  buffalo: P("Buffalo, NY", 42.8864, -78.8784),
  lackawanna: P("Lackawanna, NY", 42.8256, -78.8234),
  rochester: P("Rochester, NY", 43.1566, -77.6088),
  batavia: P("Batavia, NY", 42.9981, -78.1875),
  canandaigua: P("Canandaigua, NY", 42.8875, -77.2817),
  syracuse: P("Syracuse, NY", 43.0481, -76.1474),
  albany: P("Albany, NY", 42.6526, -73.7562),
  binghamton: P("Binghamton, NY", 42.0987, -75.918),
  jamestown: P("Jamestown, NY", 42.097, -79.2353),
  olean: P("Olean, NY", 42.0776, -78.4297),
  erie: P("Erie, PA", 42.1292, -80.0851),
  pittsburgh: P("Pittsburgh, PA", 40.4406, -79.9959),
  scranton: P("Scranton, PA", 41.409, -75.6624),
  williamsport: P("Williamsport, PA", 41.2412, -77.0011),
  cleveland: P("Cleveland, OH", 41.4993, -81.6944),
  youngstown: P("Youngstown, OH", 41.0998, -80.6495),
  toledo: P("Toledo, OH", 41.6528, -83.5379),
} satisfies Record<string, Place>;

export const DEMO_PLACE_LIST: readonly Place[] = Object.values(DEMO_PLACES);

const T = (day: number, hhmm: string) =>
  `2026-09-${String(day).padStart(2, "0")}T${hhmm}:00-04:00`;
const home = DEMO_PLACES.mountMorris;

export const DEMO_TRUCKS: readonly Truck[] = [
  {
    id: "D-101",
    tenantId: DEMO_TENANT_ID,
    name: "Dump 101",
    equipmentType: "dump",
    capacity: { weightLbs: 48_000, volumeCuYd: 80 },
    home,
    currentLocation: DEMO_PLACES.cleveland,
    availability: { earliest: T(29, "06:00"), latest: T(30, "20:00") },
    maxDeadheadMiles: 175,
    serviceRadiusMiles: 150,
    driverCost: { basis: "per-mile", amount: 0.62 },
  },
  {
    id: "D-114",
    tenantId: DEMO_TENANT_ID,
    name: "Dump 114",
    equipmentType: "dump",
    capacity: { weightLbs: 50_000, volumeCuYd: 40 },
    commodityRestrictions: {
      exclude: ["scrap-metal"],
      reason: "poly-lined body kept clean for road salt; scrap would tear the liner",
    },
    home,
    currentLocation: DEMO_PLACES.pittsburgh,
    availability: { earliest: T(29, "08:00"), latest: T(29, "23:00") },
    maxDeadheadMiles: 150,
    serviceRadiusMiles: 150,
    driverCost: { basis: "per-day", amount: 320 },
  },
  {
    id: "F-207",
    tenantId: DEMO_TENANT_ID,
    name: "Flatbed 207",
    equipmentType: "flatbed",
    capacity: { weightLbs: 48_000 },
    home,
    currentLocation: DEMO_PLACES.pittsburgh,
    availability: { earliest: T(29, "07:00"), latest: T(30, "18:00") },
    maxDeadheadMiles: 150,
    serviceRadiusMiles: 150,
    driverCost: { basis: "per-mile", amount: 0.6 },
  },
  {
    id: "F-212",
    tenantId: DEMO_TENANT_ID,
    name: "Flatbed 212",
    equipmentType: "flatbed",
    capacity: { weightLbs: 47_000 },
    home,
    currentLocation: DEMO_PLACES.albany,
    availability: { earliest: T(29, "10:00"), latest: T(30, "18:00") },
    maxDeadheadMiles: 175,
    serviceRadiusMiles: 150,
    driverCost: { basis: "per-day", amount: 300 },
  },
  {
    id: "P-301",
    tenantId: DEMO_TENANT_ID,
    name: "Pneumatic 301",
    equipmentType: "pneumatic-tanker",
    capacity: { weightLbs: 52_000 },
    home,
    currentLocation: DEMO_PLACES.rochester,
    availability: { earliest: T(29, "06:00"), latest: T(30, "18:00") },
    maxDeadheadMiles: 100,
    serviceRadiusMiles: 150,
    driverCost: { basis: "per-mile", amount: 0.62 },
    dedicatedLaneOnly: true,
    dedicatedLaneNote:
      "Dedicated lane only. Pneumatic tankers run contracted dry-bulk lanes, and a spot powder load risks contaminating the tank and missing the contract run, so this unit is not ranked against spot freight.",
  },
];

const demo = { kind: "demo" } as const;

export const DEMO_LOADS: readonly Load[] = [
  {
    id: "L-101",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.cleveland,
    destination: DEMO_PLACES.batavia,
    commodity: { name: "Crushed limestone #57", class: "aggregate" },
    weightLbs: 46_000,
    volumeCuYd: 32,
    pay: { basis: "flat", amount: 1450 },
    pickup: { earliest: T(29, "08:00"), latest: T(29, "14:00") },
    delivery: { earliest: T(29, "14:00"), latest: T(30, "12:00") },
    equipmentTypes: ["dump"],
    source: demo,
  },
  {
    id: "L-102",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.erie,
    destination: DEMO_PLACES.lackawanna,
    commodity: { name: "Shredded scrap steel", class: "scrap-metal" },
    weightLbs: 38_000,
    volumeCuYd: 55,
    pay: { basis: "flat", amount: 780 },
    pickup: { earliest: T(29, "10:00"), latest: T(29, "18:00") },
    delivery: { earliest: T(29, "12:00"), latest: T(30, "16:00") },
    equipmentTypes: ["dump"],
    source: demo,
  },
  {
    id: "L-103",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.jamestown,
    destination: DEMO_PLACES.rochester,
    commodity: { name: "Double-ground hardwood mulch", class: "mulch" },
    weightLbs: 24_000,
    volumeCuYd: 76,
    pay: { basis: "flat", amount: 1050 },
    pickup: { earliest: T(29, "09:00"), latest: T(29, "17:00") },
    delivery: { earliest: T(29, "12:00"), latest: T(30, "14:00") },
    equipmentTypes: ["dump"],
    source: demo,
  },
  {
    id: "L-104",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.pittsburgh,
    destination: DEMO_PLACES.buffalo,
    commodity: { name: "Masonry sand", class: "sand" },
    weightLbs: 47_000,
    volumeCuYd: 29,
    pay: { basis: "per-mile", rate: 2.75 },
    pickup: { earliest: T(29, "09:00"), latest: T(29, "15:00") },
    delivery: { earliest: T(29, "15:00"), latest: T(30, "10:00") },
    equipmentTypes: ["dump"],
    source: demo,
  },
  {
    id: "L-105",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.youngstown,
    destination: DEMO_PLACES.jamestown,
    commodity: { name: "Asphalt millings", class: "asphalt-millings" },
    weightLbs: 44_000,
    volumeCuYd: 30,
    pay: { basis: "flat", amount: 650 },
    pickup: { earliest: T(29, "06:00"), latest: T(29, "07:00") },
    delivery: { earliest: T(29, "09:00"), latest: T(29, "15:00") },
    equipmentTypes: ["dump"],
    source: demo,
    notes: "Paving crew needs millings at first light.",
  },
  {
    id: "L-106",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.pittsburgh,
    destination: DEMO_PLACES.buffalo,
    commodity: { name: "Hot-rolled steel coils (3)", class: "steel" },
    weightLbs: 44_000,
    pay: { basis: "flat", amount: 1350 },
    pickup: { earliest: T(29, "08:00"), latest: T(29, "16:00") },
    delivery: { earliest: T(29, "14:00"), latest: T(30, "12:00") },
    equipmentTypes: ["flatbed", "step-deck"],
    source: demo,
  },
  {
    id: "L-107",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.albany,
    destination: DEMO_PLACES.rochester,
    commodity: { name: "Kiln-dried framing lumber", class: "lumber" },
    weightLbs: 40_000,
    pay: { basis: "per-mile", rate: 2.4 },
    pickup: { earliest: T(29, "10:00"), latest: T(29, "16:00") },
    delivery: { earliest: T(29, "16:00"), latest: T(30, "14:00") },
    equipmentTypes: ["flatbed"],
    source: demo,
  },
  {
    id: "L-108",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.syracuse,
    destination: DEMO_PLACES.batavia,
    commodity: { name: "Packaging machine (crated)", class: "machinery" },
    weightLbs: 26_000,
    pay: { basis: "flat", amount: 900 },
    pickup: { earliest: T(29, "12:00"), latest: T(29, "18:00") },
    delivery: { earliest: T(30, "07:00"), latest: T(30, "15:00") },
    equipmentTypes: ["flatbed", "step-deck"],
    source: demo,
  },
  {
    id: "L-109",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.scranton,
    destination: DEMO_PLACES.canandaigua,
    commodity: { name: "Palletized concrete block", class: "building-materials" },
    weightLbs: 45_000,
    pay: { basis: "flat", amount: 1150 },
    pickup: { earliest: T(29, "11:00"), latest: T(29, "17:00") },
    delivery: { earliest: T(30, "07:00"), latest: T(30, "16:00") },
    equipmentTypes: ["flatbed"],
    source: demo,
  },
  {
    id: "L-110",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.cleveland,
    destination: DEMO_PLACES.rochester,
    commodity: { name: "Structural steel beams", class: "steel" },
    weightLbs: 49_500,
    pay: { basis: "flat", amount: 1600 },
    pickup: { earliest: T(29, "08:00"), latest: T(29, "16:00") },
    delivery: { earliest: T(29, "16:00"), latest: T(30, "16:00") },
    equipmentTypes: ["flatbed"],
    source: demo,
    notes: "Needs a light tractor — gross is tight.",
  },
  {
    id: "L-111",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.buffalo,
    destination: DEMO_PLACES.syracuse,
    commodity: { name: "Portland cement (bulk)", class: "dry-bulk-powder" },
    weightLbs: 50_000,
    pay: { basis: "flat", amount: 1100 },
    pickup: { earliest: T(29, "07:00"), latest: T(29, "15:00") },
    delivery: { earliest: T(29, "12:00"), latest: T(30, "12:00") },
    equipmentTypes: ["pneumatic-tanker"],
    source: demo,
  },
  {
    id: "L-112",
    tenantId: DEMO_TENANT_ID,
    origin: DEMO_PLACES.pittsburgh,
    destination: DEMO_PLACES.albany,
    commodity: { name: "Steel plate", class: "steel" },
    weightLbs: 42_000,
    pay: { basis: "flat", amount: 1900 },
    pickup: { earliest: T(29, "08:00"), latest: T(29, "14:00") },
    delivery: { earliest: T(30, "07:00"), latest: T(30, "17:00") },
    equipmentTypes: ["flatbed"],
    source: demo,
  },
];
