// GENERATED by scripts/set-release.mjs from store/release.json.
// Do not edit by hand -- edit store/release.json and re-run the script.

export const APP_VERSION = "1.0.0";
export const BUILD_NUMBER = "1";
