// Deterministic Markdown renderer for a ConsultingReport — used to produce the
// executive case-study documents. Pure string assembly from the report; no AI,
// no fabrication. (An AI layer could later restyle the prose; the facts here are
// fixed.)

import type { ConsultingReport, Finding } from "./types.ts";
import { BUCKET_LABEL } from "./roadmap.ts";

function findingBlock(f: Finding, n: number): string {
  const claims = f.claims
    .map((c) => `  - **${c.type.toUpperCase()}:** ${c.text}`)
    .join("\n");
  return [
    `### ${n}. ${f.label} — ${f.priority.toUpperCase()} (rated ${f.rating}/5)`,
    "",
    `1. **Finding:** ${f.finding}`,
    `2. **Supporting Evidence:**\n${f.supportingEvidence.map((e) => `   - ${e}`).join("\n")}`,
    `3. **Business Impact:** ${f.businessImpact}`,
    `4. **Root Cause (inference):** ${f.rootCause}`,
    `5. **Business Risk:** ${f.businessRisk}`,
    `6. **Opportunity:** ${f.opportunity}`,
    `7. **Priority:** ${f.priority}`,
    `8. **Recommended Action (opinion):** ${f.recommendedAction}`,
    `9. **Implementation Difficulty:** ${f.difficulty}`,
    `10. **Expected Timeline:** ${f.timeline.replace("_", " ")}`,
    `11. **Success Metrics:** ${f.successMetrics.join("; ")}`,
    `12. **Recommended Herman Legacy Services:** ${f.services.join(", ")}`,
    "",
    `_Claim classification:_`,
    claims,
    "",
  ].join("\n");
}

export function renderReportMarkdown(
  r: ConsultingReport,
  opts?: { sample?: boolean },
): string {
  const lines: string[] = [];
  const kind =
    r.mode === "analysis_only"
      ? "Internal Transformation Assessment (Analysis Only)"
      : "Executive Business Transformation Blueprint";
  lines.push(`# ${r.generatedFor} — ${kind}`);
  lines.push("");
  lines.push(
    `**Generated by:** HL-BTI Consulting Intelligence Framework \`${r.meta.engineVersion}\` (deterministic) · **Transformation Score:** ${r.transformationScore ?? "—"}/100`,
  );
  if (opts?.sample) {
    lines.push("");
    lines.push(
      `> **Illustrative sample.** The assessment ratings below are representative inputs used to demonstrate the framework, not a live client engagement. Every output still traces deterministically to the stated inputs.`,
    );
  }
  if (r.mode === "analysis_only") {
    lines.push("");
    lines.push(
      `> **Analysis only.** Recommendations for discussion. No proposal, implementation, billing, or migration.`,
    );
  }

  // Narrative
  lines.push("\n## Executive Narrative\n");
  for (const s of r.narrative) {
    lines.push(`### ${s.title}`);
    lines.push(s.hasData ? s.body : `_Not available — ${s.note}_`);
    lines.push("");
  }

  // Findings
  lines.push(`## Consulting Findings (${r.findings.length})\n`);
  if (r.findings.length === 0)
    lines.push(
      "_No findings — nothing was rated at or below the finding threshold._\n",
    );
  r.findings.forEach((f, i) => lines.push(findingBlock(f, i + 1)));

  // Roadmap
  lines.push("## Transformation Roadmap\n");
  const buckets: [string, typeof r.roadmap.immediate][] = [
    [BUCKET_LABEL.immediate, r.roadmap.immediate],
    [BUCKET_LABEL.short_term, r.roadmap.shortTerm],
    [BUCKET_LABEL.medium_term, r.roadmap.mediumTerm],
    [BUCKET_LABEL.long_term, r.roadmap.longTerm],
  ];
  for (const [title, items] of buckets) {
    lines.push(`### ${title}`);
    if (items.length === 0) lines.push("_None._");
    else
      for (const it of items)
        lines.push(
          `- **${it.label}** (${it.priority}) — ${it.action}\n  - _${it.justification}_`,
        );
    lines.push("");
  }

  // Solutions
  lines.push("## Recommended Herman Legacy Services\n");
  if (r.solutions.length === 0)
    lines.push("_None recommended — no supporting findings._\n");
  else for (const s of r.solutions) lines.push(`- **${s.service}** — ${s.rationale}`);
  lines.push("");

  // Financial
  lines.push("## Financial Framework\n");
  for (const l of r.financial) {
    lines.push(
      `- **${l.label}:** ${l.value === null ? "_" + l.note + "_" : `${l.value.toLocaleString()} ${l.unit} (${l.note})`}`,
    );
  }
  lines.push("");

  // CEO review
  lines.push("## CEO Review Package\n");
  if (r.review.length === 0) lines.push("_No findings to review._\n");
  for (const it of r.review) {
    lines.push(`### ${it.subject} — confidence: ${it.confidence}`);
    lines.push(`- **Evidence used:** ${it.evidenceUsed.join("; ")}`);
    lines.push(`- **Missing information:** ${it.missingInformation.join("; ")}`);
    lines.push(`- **Recommended next questions:** ${it.nextQuestions.join(" ")}`);
    lines.push("");
  }

  // Meta
  lines.push("## Provenance\n");
  lines.push(
    `Domains assessed: ${r.meta.domainsAssessed} · Dimensions rated: ${r.meta.dimensionsRated} · Findings: ${r.meta.findingsGenerated} · ` +
      `Claims — FACT: ${r.meta.factCount}, INFERENCE: ${r.meta.inferenceCount}, OPINION: ${r.meta.opinionCount}.`,
  );
  lines.push("");
  return lines.join("\n");
}
