/**
 * The ATS Resume Optimizer domain model.
 *
 * One rule shapes every type in this file: a FACT and a WORDING are different
 * things, and the type system is not allowed to blur them.
 *
 *   - A `CareerFact` is something that is true about the candidate. It carries
 *     a `source` saying how we know it.
 *   - A `GeneratedLine` is wording we produced. It carries the evidence it was
 *     derived from and a validation verdict.
 *
 * Wording may rephrase, reorder, compress and emphasise a fact. It may never
 * introduce one. Every generator in this package returns `GeneratedLine`s, and
 * `validateClaim()` is the only thing that may stamp one `verified`.
 */

/** Every record is keyed by a UUID (RFC 4122 v4, generated by `newId()`). */
export type UUID = string;

/** ISO-8601 timestamp, always UTC. */
export type Timestamp = string;

/** Fields every persisted record carries. */
export interface RecordMeta {
  readonly id: UUID;
  readonly createdAt: Timestamp;
  readonly updatedAt: Timestamp;
}

// ---------------------------------------------------------------------------
// Provenance
// ---------------------------------------------------------------------------

/**
 * How we know a fact.
 *
 * `generated_wording` is deliberately NOT a way to introduce a fact. A fact
 * whose source is `generated_wording` is a rephrasing of other facts, and it
 * must name them in `derivedFrom`. See `validateClaim()`.
 */
export type SourceStatus = "resume" | "user_confirmed" | "generated_wording";

/** Where a claim ended up after validation. */
export type ValidationStatus =
  "verified" | "user_confirmed" | "needs_confirmation" | "unsupported";

/** Only these two may be written into an exported document. */
export const EXPORTABLE_STATUSES: readonly ValidationStatus[] = [
  "verified",
  "user_confirmed",
];

// ---------------------------------------------------------------------------
// Candidate profile — the structured career database
// ---------------------------------------------------------------------------

export type FactCategory =
  | "identity"
  | "contact"
  | "headline"
  | "summary"
  | "employment"
  | "responsibility"
  | "accomplishment"
  | "metric"
  | "scope"
  | "industry"
  | "software"
  | "technical_skill"
  | "leadership_skill"
  | "operational_skill"
  | "certification"
  | "license"
  | "education"
  | "award"
  | "volunteer"
  | "project"
  | "military"
  | "other";

/**
 * One atomic, checkable statement about the candidate.
 *
 * `text` is what is true. `numbers` is every quantity the statement asserts,
 * extracted once at write time so the claim validator never has to re-parse
 * prose to find out whether "85 routes" is supported.
 */
export interface CareerFact extends RecordMeta {
  readonly profileId: UUID;
  readonly category: FactCategory;
  readonly text: string;
  readonly source: SourceStatus;
  /** Employer / role this fact belongs to, when it belongs to one. */
  readonly context?: string;
  /** Quantities asserted by `text`, normalised (see `extractNumbers`). */
  readonly numbers: readonly string[];
  /** For `generated_wording` only: the fact ids this wording came from. */
  readonly derivedFrom?: readonly UUID[];
  /** Sample/demo data is marked here and surfaced in the UI as such. */
  readonly isSample?: boolean;
}

export interface ContactInfo {
  readonly email?: string;
  readonly phone?: string;
  readonly location?: string;
  readonly linkedin?: string;
  readonly website?: string;
}

export interface CandidateProfile extends RecordMeta {
  readonly userId: UUID;
  readonly fullName: string;
  readonly headline: string;
  readonly summary: string;
  readonly contact: ContactInfo;
  readonly isSample?: boolean;
}

// ---------------------------------------------------------------------------
// Resume
// ---------------------------------------------------------------------------

export interface ExperienceEntry {
  readonly id: UUID;
  readonly title: string;
  readonly employer: string;
  readonly location?: string;
  readonly startDate?: string;
  readonly endDate?: string;
  readonly current: boolean;
  readonly bullets: readonly string[];
}

export interface EducationEntry {
  readonly id: UUID;
  readonly credential: string;
  readonly institution: string;
  readonly location?: string;
  readonly year?: string;
}

/** The canonical ATS section set. Order here is the default render order. */
export type SectionKind =
  | "header"
  | "summary"
  | "skills"
  | "experience"
  | "education"
  | "certifications"
  | "projects"
  | "additional";

export interface ParsedResume {
  readonly fullName: string;
  readonly contact: ContactInfo;
  readonly headline: string;
  readonly summary: readonly string[];
  readonly skills: readonly string[];
  readonly experience: readonly ExperienceEntry[];
  readonly education: readonly EducationEntry[];
  readonly certifications: readonly string[];
  readonly projects: readonly string[];
  readonly additional: readonly string[];
  /** Sections the parser could not confidently place, kept rather than dropped. */
  readonly unparsed: readonly string[];
}

export type ResumeIngestFormat = "paste" | "docx" | "pdf";

/** A master resume: the raw original plus the structured reading of it. */
export interface MasterResume extends RecordMeta {
  readonly profileId: UUID;
  readonly label: string;
  readonly format: ResumeIngestFormat;
  readonly rawText: string;
  readonly parsed: ParsedResume;
  readonly isDefault: boolean;
  readonly isSample?: boolean;
}

// ---------------------------------------------------------------------------
// Job posting
// ---------------------------------------------------------------------------

export type RequirementImportance =
  "critical" | "important" | "preferred" | "informational";

export type RequirementKind =
  | "qualification"
  | "experience"
  | "education"
  | "certification"
  | "software"
  | "hard_skill"
  | "soft_skill"
  | "leadership"
  | "responsibility"
  | "compliance"
  | "travel"
  | "physical"
  | "scope";

export interface JobRequirement {
  readonly id: UUID;
  readonly text: string;
  readonly kind: RequirementKind;
  readonly importance: RequirementImportance;
  /** Which part of the posting it came from — kept for auditability. */
  readonly sourceSection: string;
  /** Normalised terms this requirement is "about". */
  readonly terms: readonly string[];
  /** e.g. 5 for "5+ years of experience". */
  readonly yearsRequired?: number;
}

export type KeywordPriority = "high" | "medium" | "low";

export interface JobKeyword {
  readonly id: UUID;
  readonly term: string;
  readonly priority: KeywordPriority;
  readonly occurrences: number;
  /** Whether the term appears in a critical/important requirement. */
  readonly inRequirement: boolean;
}

export interface JobFacets {
  readonly employmentType?: string;
  readonly compensation?: string;
  readonly yearsOfExperience?: number;
  readonly educationRequirement?: string;
  readonly certifications: readonly string[];
  readonly software: readonly string[];
  readonly hardSkills: readonly string[];
  readonly softSkills: readonly string[];
  readonly leadership: readonly string[];
  readonly responsibilities: readonly string[];
  readonly industryTerms: readonly string[];
  readonly actionVerbs: readonly string[];
  readonly managementScope: readonly string[];
  readonly budgetExpectations: readonly string[];
  readonly compliance: readonly string[];
  readonly travel?: string;
  readonly physical?: string;
}

export interface JobPosting extends RecordMeta {
  readonly profileId: UUID;
  readonly company: string;
  readonly title: string;
  readonly location?: string;
  readonly url?: string;
  readonly rawText: string;
  readonly facets: JobFacets;
  readonly requirements: readonly JobRequirement[];
  readonly keywords: readonly JobKeyword[];
  readonly isSample?: boolean;
}

// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------

export type MatchStatus =
  "strong_match" | "partial_match" | "terminology_match" | "not_evidenced";

/** One row of the evidence matrix. */
export interface RequirementMatch {
  readonly id: UUID;
  readonly requirementId: UUID;
  readonly requirement: string;
  readonly importance: RequirementImportance;
  /** The candidate's own wording, quoted. Empty when nothing was found. */
  readonly evidence: string;
  /** Where that wording came from, e.g. "Amazon — Operations Manager". */
  readonly evidenceSource: string;
  readonly evidenceFactIds: readonly UUID[];
  readonly status: MatchStatus;
  readonly recommendedAction: string;
  readonly suggestedPlacement: readonly SectionKind[];
  /** 0..1 — how much of the requirement the evidence covers. */
  readonly coverage: number;
}

export interface TerminologyOpportunity {
  readonly id: UUID;
  readonly resumeWording: string;
  readonly jobWording: string;
  readonly recommendedRewrite: string;
  readonly evidenceFactIds: readonly UUID[];
  readonly requirementIds: readonly UUID[];
}

export interface KeywordAnalysis {
  readonly present: readonly JobKeyword[];
  /** Missing from the resume, but the candidate's evidence supports them. */
  readonly supportedMissing: readonly JobKeyword[];
  /** Missing, and nothing in the profile supports them. Never auto-inserted. */
  readonly unsupported: readonly JobKeyword[];
}

export interface ScoreBreakdown {
  readonly qualificationAlignment: number;
  readonly relevantExperience: number;
  readonly skillsAndKeywords: number;
  readonly quantifiedAccomplishments: number;
  readonly atsStructure: number;
}

/**
 * An INTERNAL optimisation score. It is not, and cannot be, the employer's ATS
 * score: we do not know their system, their weights, or their cutoffs. Every
 * surface that shows this number must say so.
 */
export interface MatchScore {
  readonly overall: number;
  readonly breakdown: ScoreBreakdown;
  readonly weights: ScoreBreakdown;
  readonly explanation: readonly string[];
}

export interface AtsFormatFinding {
  readonly id: UUID;
  readonly severity: "risk" | "warning" | "ok";
  readonly message: string;
  readonly fix: string;
}

export interface JobAnalysis extends RecordMeta {
  readonly profileId: UUID;
  readonly resumeId: UUID;
  readonly jobPostingId: UUID;
  readonly matches: readonly RequirementMatch[];
  readonly keywords: KeywordAnalysis;
  readonly terminology: readonly TerminologyOpportunity[];
  readonly scoreBefore: MatchScore;
  readonly scoreProjected: MatchScore;
  readonly formatFindings: readonly AtsFormatFinding[];
  readonly recommendations: readonly string[];
  /** Which engine produced this: the built-in rules engine, or Claude. */
  readonly engine: string;
  readonly isSample?: boolean;
}

// ---------------------------------------------------------------------------
// Generated resume
// ---------------------------------------------------------------------------

/**
 * One generated sentence, plus everything needed to audit it.
 *
 * The review screen reads exactly these fields to answer "why does this line
 * say what it says" — source evidence, the requirement it addresses, and the
 * reason the wording was recommended.
 */
export interface GeneratedLine {
  readonly id: UUID;
  readonly section: SectionKind;
  /** Grouping key inside a section, e.g. the experience entry id. */
  readonly groupId?: string;
  readonly text: string;
  /** The candidate's original wording, when this is a rewrite of one. */
  readonly originalText?: string;
  readonly evidenceFactIds: readonly UUID[];
  readonly evidenceText: readonly string[];
  readonly addressesRequirementIds: readonly UUID[];
  readonly rationale: string;
  readonly validation: ValidationStatus;
  /** Populated when validation is not `verified`. */
  readonly validationNotes: readonly string[];
}

export interface GeneratedResume extends RecordMeta {
  readonly profileId: UUID;
  readonly analysisId: UUID;
  readonly resumeId: UUID;
  readonly jobPostingId: UUID;
  readonly versionNumber: number;
  readonly company: string;
  readonly jobTitle: string;
  readonly fullName: string;
  readonly contact: ContactInfo;
  readonly headline: GeneratedLine;
  readonly summary: readonly GeneratedLine[];
  readonly competencies: readonly string[];
  readonly experience: readonly GeneratedExperience[];
  readonly education: readonly EducationEntry[];
  readonly certifications: readonly string[];
  readonly additional: readonly string[];
  readonly sectionOrder: readonly SectionKind[];
  readonly engine: string;
  readonly isSample?: boolean;
}

export interface GeneratedExperience {
  readonly entryId: UUID;
  readonly title: string;
  readonly employer: string;
  readonly location?: string;
  readonly startDate?: string;
  readonly endDate?: string;
  readonly current: boolean;
  readonly bullets: readonly GeneratedLine[];
  /** Why this entry sits where it does in the ordering. */
  readonly relevanceNote: string;
  readonly relevance: number;
}

// ---------------------------------------------------------------------------
// Applications, cover letters, interview prep
// ---------------------------------------------------------------------------

export type ApplicationStatus =
  | "researching"
  | "resume_created"
  | "applied"
  | "recruiter_screen"
  | "interviewing"
  | "final_interview"
  | "offer"
  | "rejected"
  | "withdrawn"
  | "closed";

export interface Application extends RecordMeta {
  readonly profileId: UUID;
  readonly company: string;
  readonly role: string;
  readonly jobUrl?: string;
  readonly jobPostingId?: UUID;
  readonly analysisId?: UUID;
  readonly generatedResumeId?: UUID;
  readonly coverLetterId?: UUID;
  readonly dateAnalyzed?: string;
  readonly dateApplied?: string;
  readonly status: ApplicationStatus;
  readonly recruiterName?: string;
  readonly recruiterContact?: string;
  readonly interviewDates: readonly string[];
  readonly notes: string;
  readonly isSample?: boolean;
}

export interface CoverLetter extends RecordMeta {
  readonly profileId: UUID;
  readonly analysisId: UUID;
  readonly company: string;
  readonly jobTitle: string;
  readonly greeting: string;
  readonly paragraphs: readonly GeneratedLine[];
  readonly closing: string;
  readonly engine: string;
  readonly isSample?: boolean;
}

export type InterviewQuestionKind =
  "strength" | "gap" | "leadership" | "technical" | "behavioural";

export interface InterviewQuestion {
  readonly id: UUID;
  readonly kind: InterviewQuestionKind;
  readonly question: string;
  readonly why: string;
  /** STAR scaffolding built from real experience — never a scripted answer. */
  readonly starPrompts: readonly string[];
  readonly evidenceFactIds: readonly UUID[];
  readonly requirementIds: readonly UUID[];
}

export interface InterviewPrep extends RecordMeta {
  readonly profileId: UUID;
  readonly analysisId: UUID;
  readonly questions: readonly InterviewQuestion[];
  /** Partial matches and gaps: the things to have an honest answer ready for. */
  readonly explainThese: readonly InterviewQuestion[];
  readonly engine: string;
  readonly isSample?: boolean;
}

export interface UserSetting extends RecordMeta {
  readonly userId: UUID;
  readonly key: string;
  readonly value: string;
}
