/**
 * Generate the capability-extraction migration from the source-controlled
 * capability vocabulary.
 *
 * Same reason as build-scoring-sql.mts and build-portfolio-sql.mts: the terms
 * that decide what counts as "route optimization" must be reviewable in
 * TypeScript and covered by vitest, but the extraction has to run inside the
 * database across 62,250 rows. Generating the SQL keeps one definition rather
 * than two that drift.
 *
 * The generated function mirrors extractCapabilities() exactly:
 *   * strong terms carry a claim, weak terms only corroborate;
 *   * the strongest artifact wins, description > topics > name;
 *   * `title` is NOT part of the description haystack, because in this corpus
 *     it is literally "owner/repo" and would let a name match score as a
 *     description;
 *   * claims below the confidence floor are dropped, not stored weakly.
 *
 * Usage: tsx scripts/build-capability-sql.mts [--out FILE]
 */
import { writeFileSync } from "node:fs";
import {
  CAPABILITIES,
  ASSET_RULES,
  EVIDENCE_WEIGHT,
  CAPABILITY_ENGINE_VERSION,
  MAX_CAPABILITIES_PER_OPPORTUNITY,
  MIN_CAPABILITY_CONFIDENCE,
  MAX_ASSETS_PER_OPPORTUNITY,
} from "../packages/venture-studio/src/capability.ts";

const outIdx = process.argv.indexOf("--out");
const OUT =
  outIdx > -1
    ? String(process.argv[outIdx + 1])
    : "supabase/migrations/20260820340000_hlbos_0044_capability_extraction.sql";

const q = (v: string): string => `'${v.replace(/'/g, "''")}'`;
/** A regex alternation with \m..\M word boundaries, matching containsTerm. */
const alt = (xs: readonly string[]): string =>
  q(
    `\\m(${[...xs]
      .sort((a, b) => b.length - a.length)
      .map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
      .join("|")})\\M`,
  );

const seed = CAPABILITIES.map(
  (c) =>
    `  (${q(c.slug)}, ${q(c.label)}, ${q(c.capType)}, ${q(c.domain)}, ${q(c.description)}, ${q(c.hlgVertical)}, ${q(CAPABILITY_ENGINE_VERSION)})`,
).join(",\n");

const capBranches = CAPABILITIES.map(
  (c) => `    (${q(c.slug)}, ${alt(c.strongTerms)}, ${alt(c.weakTerms)})`,
).join(",\n");

const assetBranches = ASSET_RULES.map(
  (r) => `    (${q(r.kind)}, ${q(r.label)}, ${alt(r.terms)})`,
).join(",\n");

const sql = `-- hlbos_0044: run capability extraction across the supply universe
--
-- GENERATED by scripts/build-capability-sql.mts from
-- packages/venture-studio/src/capability.ts (${CAPABILITY_ENGINE_VERSION}).
-- Do not hand-edit: change the TypeScript, run the generator, review the diff.
-- The TypeScript is the definition and is covered by vitest; this file is how
-- that definition runs over 62,250 rows without leaving the database.
--
-- WHAT IT DOES
-- Reads only metadata HLVS already holds -- description, topics, name, language,
-- licence. No network call, no model, no new evidence. A capability is claimed
-- only where a STRONG term appears; weak terms raise confidence but can never
-- create a claim on their own. That single rule is what stops every project
-- with the word "routing" in it being labelled a logistics product.
--
-- Claims below ${MIN_CAPABILITY_CONFIDENCE} confidence are dropped rather than stored weakly, and a
-- repository with no qualifying evidence simply gets no capability. An honest
-- blank is the correct answer for software we cannot describe from metadata.
--
-- rollback:
--   drop function if exists vstudio.extract_capabilities(text);
--   drop function if exists vstudio.extract_capability_categories();
--   delete from vstudio.opportunity_capabilities where engine_version = ${q(CAPABILITY_ENGINE_VERSION)};
--   delete from vstudio.opportunity_reusable_assets where engine_version = ${q(CAPABILITY_ENGINE_VERSION)};
--   delete from vstudio.capabilities where engine_version = ${q(CAPABILITY_ENGINE_VERSION)};
--   No opportunity, score, portfolio or pain row is touched in either direction.

-- ---------------------------------------------------------------------------
-- The vocabulary, seeded from source control
-- ---------------------------------------------------------------------------
insert into vstudio.capabilities (slug, label, cap_type, domain, description, hlg_vertical, engine_version)
values
${seed}
on conflict (slug) do update set
  label = excluded.label, cap_type = excluded.cap_type, domain = excluded.domain,
  description = excluded.description, hlg_vertical = excluded.hlg_vertical,
  engine_version = excluded.engine_version;

-- ---------------------------------------------------------------------------
-- Work enumeration, so a full run can be batched by category
-- ---------------------------------------------------------------------------
create or replace function vstudio.extract_capability_categories()
returns table (category text)
language sql stable security definer set search_path = '' as $fn$
  select distinct o.category from vstudio.opportunities o order by 1
$fn$;
revoke all on function vstudio.extract_capability_categories() from public, anon;
grant execute on function vstudio.extract_capability_categories() to authenticated;

-- ---------------------------------------------------------------------------
-- Extraction for one category partition
-- ---------------------------------------------------------------------------
create or replace function vstudio.extract_capabilities(p_category text)
returns integer
language plpgsql volatile security definer set search_path = '' as $fn$
declare v_rows integer;
begin
  perform vstudio.assert_intelligence_manage();

  with base as (
    select
      o.id, o.license,
      -- summary ONLY: o.title is "owner/repo" in this corpus, so including it
      -- here would let a repository name score as a written description.
      pg_catalog.regexp_replace(pg_catalog.lower(coalesce(o.summary,'')), '[_/\\\\.-]+', ' ', 'g') as descr,
      pg_catalog.regexp_replace(pg_catalog.lower(pg_catalog.array_to_string(coalesce(o.topics,'{}'::text[]), ' ')), '[_/\\\\.-]+', ' ', 'g') as topics,
      pg_catalog.regexp_replace(pg_catalog.lower(pg_catalog.regexp_replace(coalesce(o.repository_url, o.title), '^https?://github[.]com/', '')), '[_/\\\\.-]+', ' ', 'g') as nm
    from vstudio.opportunities o
    where o.category is not distinct from p_category
  ),
  vocab (slug, strong_re, weak_re) as (values
${capBranches}
  ),
  hits as (
    select b.id, v.slug,
      -- Strongest artifact carrying a strong term. The ordering of these three
      -- CASE arms is the evidence hierarchy.
      case
        when b.descr  ~ v.strong_re then 'description'
        when b.topics ~ v.strong_re then 'topics'
        when b.nm     ~ v.strong_re then 'name'
      end as evidence_kind,
      case
        when b.descr  ~ v.strong_re then (pg_catalog.regexp_match(b.descr,  v.strong_re))[1]
        when b.topics ~ v.strong_re then (pg_catalog.regexp_match(b.topics, v.strong_re))[1]
        when b.nm     ~ v.strong_re then (pg_catalog.regexp_match(b.nm,     v.strong_re))[1]
      end as excerpt,
      -- Corroboration: distinct weak terms anywhere in description or topics.
      (select count(distinct m[1]) from pg_catalog.regexp_matches(b.descr || ' ' || b.topics, v.weak_re, 'g') m) as weak_hits
    from base b join vocab v
      on b.descr ~ v.strong_re or b.topics ~ v.strong_re or b.nm ~ v.strong_re
  ),
  scored as (
    select h.id, h.slug, h.evidence_kind, h.excerpt,
      pg_catalog.round(
        (case h.evidence_kind
           when 'description' then ${EVIDENCE_WEIGHT.description}::numeric
           when 'topics'      then ${EVIDENCE_WEIGHT.topics}::numeric
           else                    ${EVIDENCE_WEIGHT.name}::numeric end)
        * (0.7 + 0.3 * least(1::numeric, h.weak_hits::numeric / 3)) * 100)::int as confidence
    from hits h
  ),
  ranked as (
    select s.*, row_number() over (
      partition by s.id order by s.confidence desc, s.slug) as rn
    from scored s
    where s.confidence >= ${MIN_CAPABILITY_CONFIDENCE}
  )
  insert into vstudio.opportunity_capabilities
    (opportunity_id, capability_slug, is_primary, evidence_kind, evidence_excerpt,
     evidence_locator, confidence, confidence_status, extraction_level, engine_version, extracted_at)
  select r.id, r.slug, r.rn = 1, r.evidence_kind,
         pg_catalog.left(coalesce(r.excerpt,''), 400),
         case r.evidence_kind
           when 'description' then 'repository description'
           when 'topics'      then 'repository topics'
           else 'repository name' end,
         r.confidence, 'estimated', 1, ${q(CAPABILITY_ENGINE_VERSION)}, pg_catalog.now()
  from ranked r
  where r.rn <= ${MAX_CAPABILITIES_PER_OPPORTUNITY}
  on conflict (opportunity_id, capability_slug) do update set
    is_primary = excluded.is_primary,
    evidence_kind = excluded.evidence_kind,
    evidence_excerpt = excluded.evidence_excerpt,
    evidence_locator = excluded.evidence_locator,
    confidence = excluded.confidence,
    extraction_level = excluded.extraction_level,
    engine_version = excluded.engine_version,
    extracted_at = excluded.extracted_at;

  get diagnostics v_rows = row_count;

  -- --- reusable assets, same evidence discipline -----------------------------
  with base as (
    select o.id, o.license,
      pg_catalog.regexp_replace(pg_catalog.lower(coalesce(o.summary,'')), '[_/\\\\.-]+', ' ', 'g') as descr,
      pg_catalog.regexp_replace(pg_catalog.lower(pg_catalog.array_to_string(coalesce(o.topics,'{}'::text[]), ' ')), '[_/\\\\.-]+', ' ', 'g') as topics
    from vstudio.opportunities o
    where o.category is not distinct from p_category
  ),
  rules (kind, label, term_re) as (values
${assetBranches}
  ),
  found as (
    select b.id, r.kind, r.label, b.license,
      case when b.descr ~ r.term_re then 'description' else 'topics' end as evidence_kind,
      case when b.descr ~ r.term_re then (pg_catalog.regexp_match(b.descr, r.term_re))[1]
           else (pg_catalog.regexp_match(b.topics, r.term_re))[1] end as excerpt,
      case when b.descr ~ r.term_re then ${Math.round(EVIDENCE_WEIGHT.description * 100)}
           else ${Math.round(EVIDENCE_WEIGHT.topics * 100)} end as confidence
    from base b join rules r on b.descr ~ r.term_re or b.topics ~ r.term_re
  ),
  ranked_assets as (
    select f.*, row_number() over (
      partition by f.id order by f.confidence desc, f.label) as rn
    from found f
  )
  insert into vstudio.opportunity_reusable_assets
    (opportunity_id, asset_kind, label, evidence_kind, evidence_excerpt, licence,
     licence_permits_commercial, confidence, confidence_status, extraction_level,
     engine_version, extracted_at)
  select a.id, a.kind, a.label, a.evidence_kind,
         pg_catalog.left(coalesce(a.excerpt,''), 400),
         a.license,
         -- NULL, not false, when the licence is unknown or unrecognised:
         -- "we do not know" and "not permitted" are different answers.
         case
           when a.license is null or a.license = 'NOASSERTION' then null
           when a.license = any(array['MIT','Apache-2.0','BSD-2-Clause','BSD-3-Clause','ISC','0BSD','Unlicense','MPL-2.0','Zlib','BSL-1.0','PostgreSQL','Artistic-2.0','CC0-1.0']) then true
           when a.license = any(array['GPL-2.0','GPL-3.0','AGPL-3.0','LGPL-2.1','LGPL-3.0','EUPL-1.2','OSL-3.0']) then false
           else null end,
         a.confidence, 'estimated', 1, ${q(CAPABILITY_ENGINE_VERSION)}, pg_catalog.now()
  from ranked_assets a
  where a.rn <= ${MAX_ASSETS_PER_OPPORTUNITY}
  on conflict (opportunity_id, asset_kind, label) do update set
    evidence_kind = excluded.evidence_kind,
    evidence_excerpt = excluded.evidence_excerpt,
    licence = excluded.licence,
    licence_permits_commercial = excluded.licence_permits_commercial,
    confidence = excluded.confidence,
    engine_version = excluded.engine_version,
    extracted_at = excluded.extracted_at;

  return v_rows;
end;
$fn$;
revoke all on function vstudio.extract_capabilities(text) from public, anon;
grant execute on function vstudio.extract_capabilities(text) to authenticated;
comment on function vstudio.extract_capabilities(text) is
  'Level-1 capability extraction for one discovery category. Deterministic, metadata-only, evidence-backed. Generated from packages/venture-studio/src/capability.ts -- edit the TypeScript, not this.';
`;

writeFileSync(OUT, sql);
console.log(
  `wrote ${OUT} (${sql.length} bytes, ${CAPABILITIES.length} capabilities, ${ASSET_RULES.length} asset rules)`,
);
