/**
 * Generate the portfolio-building migration from the source-controlled
 * portfolio definitions.
 *
 * Same reason as scripts/build-scoring-sql.mts: the category lists that decide
 * what counts as "logistics" must be reviewable in TypeScript and tested by
 * vitest, but the selection has to run inside the database over 62,250 rows.
 * Generating the SQL means there is one definition, not two that drift.
 *
 * Usage: tsx scripts/build-portfolio-sql.mts [--out FILE]
 */
import { writeFileSync } from "node:fs";
import {
  CORE_PORTFOLIOS,
  MIN_CORE_TERMS_WITHOUT_CATEGORY,
  QUALIFICATION_THRESHOLD,
} from "../packages/venture-studio/src/portfolios.ts";
import { SCORING_VERSION } from "../packages/venture-studio/src/scoring.ts";

const outIdx = process.argv.indexOf("--out");
const OUT =
  outIdx > -1
    ? String(process.argv[outIdx + 1])
    : "supabase/migrations/20260820160000_hlbos_0035_vstudio_portfolios.sql";

const q = (v: string): string => `'${v.replace(/'/g, "''")}'`;
const arr = (xs: readonly string[]): string => `array[${xs.map(q).join(",")}]`;

/**
 * The domain-value branch for one portfolio, mirroring matchPortfolio():
 * a discovery-category hit is provenance and worth 0.6 on its own, term hits
 * saturate at four, and the two combine to at most 1.
 */
const branches = CORE_PORTFOLIOS.map((p) => {
  const core = `coalesce(jsonb_array_length(p_matched->${q(p.key)}->'core'), 0)`;
  const sup = `coalesce(jsonb_array_length(p_matched->${q(p.key)}->'sup'), 0)`;
  const strength = `(least(4::numeric, ${core}::numeric + 0.5 * ${sup}::numeric) / 4)`;
  return `    when ${q(p.key)} then
      case
        when p_category = any(${arr(p.categories)})
          then least(1::numeric, 0.6 + 0.4 * ${strength})
        when ${core} >= ${MIN_CORE_TERMS_WITHOUT_CATEGORY}
          then least(1::numeric, 0.35 + 0.65 * ${strength})
        else 0::numeric
      end`;
}).join("\n");

const sql = `-- ===========================================================================
-- hlbos_0035_vstudio_portfolios — building the Top-100 selections
--
-- GENERATED FILE. Do not edit by hand.
-- Generated by scripts/build-portfolio-sql.mts from
--   packages/venture-studio/src/portfolios.ts
--
-- A Top-100 is a SAVED RANKED VIEW over the discovery universe. Building one
-- selects and orders; it never removes, hides or rewrites a corpus record.
-- Every write here goes to vstudio.portfolio_snapshots and
-- vstudio.portfolio_members. vstudio.opportunities is read-only throughout.
--
-- WHY SNAPSHOTS RATHER THAN A LIVE QUERY
--
-- The brief requires that if the evidence changes the rankings can change —
-- and equally, that a ranking already shown to the CEO stays explicable. A
-- live query gives the first and destroys the second: last week's number 3
-- becomes unreconstructable the moment a repository gains stars. So each build
-- writes a new immutable snapshot with the scores copied in, and exactly one
-- snapshot per portfolio is flagged current.
--
-- NO HARD-CODED MEMBERS. Nothing here names a repository. Membership is
-- derived from stored scores and stored match evidence every time, which is
-- what makes the ranking reproducible rather than asserted.
--
-- HONEST COUNTS. Each snapshot records corpus_size, eligible_count and
-- member_count. If only 71 records qualify, the snapshot says 71 and the UI
-- shows 71 — a short list is never padded or presented as a full hundred.
--
-- rollback: (manual, pre-approval only)
--   DROP FUNCTION IF EXISTS vstudio.build_portfolio(text);
--   DROP FUNCTION IF EXISTS vstudio.portfolio_candidates(text);
--   DROP FUNCTION IF EXISTS vstudio.portfolio_domain_value(text, text, jsonb);
--   DELETE FROM vstudio.portfolio_members;   -- cascades from snapshots anyway
--   DELETE FROM vstudio.portfolio_snapshots;
--
-- VERIFICATION (after apply): vstudio.build_portfolio(k) for each of
--   'logistics','transformation','sports','outside-core' returns a snapshot id,
--   and each snapshot carries member_count = least(100, eligible_count).
--   pgTAP: supabase/tests/35_vstudio_portfolios.sql.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- How strongly one opportunity belongs to one portfolio's domain, 0-1.
--
-- Reads the term evidence Level-1 triage already stored rather than re-running
-- the match. Matching twice with two implementations is how a record ends up
-- ranked into a portfolio it does not belong in.
-- ---------------------------------------------------------------------------
create or replace function vstudio.portfolio_domain_value(
  p_key text, p_category text, p_matched jsonb
) returns numeric
language sql immutable as $fn$
  select case p_key
${branches}
    else 0::numeric
  end;
$fn$;
comment on function vstudio.portfolio_domain_value(text, text, jsonb) is
  'Domain match strength 0-1, mirroring matchPortfolio() in packages/venture-studio/src/portfolios.ts. A discovery-category hit is provenance and outweighs vocabulary; term hits saturate at four.';

-- ---------------------------------------------------------------------------
-- Every opportunity ELIGIBLE for one portfolio, with the score that orders it.
--
-- A separate function rather than a repeated predicate: the snapshot's
-- eligible_count and the member list must be computed from the same rule, and
-- writing that rule twice is how a snapshot ends up claiming 412 eligible while
-- ranking a different 412.
--
-- Outside-core is defined by EXCLUSION on purpose. It exists to break tunnel
-- vision, so it takes what the core domains did not claim and ranks it on
-- demonstrated demand rather than on how much it resembles what HLG already does.
-- ---------------------------------------------------------------------------
create or replace function vstudio.portfolio_candidates(p_key text)
returns table (
  opportunity_id uuid,
  popularity_score integer,
  popularity_status vstudio.metric_status,
  suitability_score integer,
  suitability_status vstudio.metric_status,
  rising_score integer,
  domain_value numeric,
  best_core_value numeric,
  matched_terms jsonb,
  category text,
  rank_score integer,
  tie_score integer
)
language sql stable security definer set search_path = '' as $fn$
  select
    o.id,
    s.popularity_score, s.popularity_status,
    s.suitability_score, s.suitability_status,
    s.rising_score,
    vstudio.portfolio_domain_value(p_key, o.category, s.evidence->'matched'),
    (s.evidence->>'best_core_value')::numeric,
    s.evidence->'matched'->p_key,
    o.category,
    case when p.rank_by = 'popularity' then s.popularity_score else s.suitability_score end,
    case when p.rank_by = 'popularity' then s.suitability_score else s.popularity_score end
  from vstudio.opportunities o
  join vstudio.opportunity_scores s
    on s.opportunity_id = o.id and s.scoring_version = ${q(SCORING_VERSION)}
  join vstudio.portfolios p on p.key = p_key
  where case
    when p_key = 'outside-core'
      then (s.evidence->>'best_core_value')::numeric < ${QUALIFICATION_THRESHOLD}
           and s.popularity_score is not null
    else vstudio.portfolio_domain_value(p_key, o.category, s.evidence->'matched') >= ${QUALIFICATION_THRESHOLD}
         and s.suitability_score is not null
  end;
$fn$;
revoke all on function vstudio.portfolio_candidates(text) from public, anon;
grant execute on function vstudio.portfolio_candidates(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Build one portfolio: a fresh immutable snapshot plus its ranked members.
-- ---------------------------------------------------------------------------
create or replace function vstudio.build_portfolio(p_key text)
returns uuid
language plpgsql volatile security definer set search_path = '' as $fn$
declare
  v_def       vstudio.portfolios%rowtype;
  v_snapshot  uuid;
  v_corpus    integer;
  v_eligible  integer;
  v_members   integer;
  v_version   text := ${q(SCORING_VERSION)};
begin
  -- Recomputing a ranking is a privilege distinct from reading one. session_user
  -- rather than current_user: inside a definer function current_user is the
  -- owner and would admit everybody. A direct maintenance connection is the
  -- platform operating on itself and is not reachable from a browser.
  if session_user not in ('postgres', 'supabase_admin')
     and not identity.has_platform_permission('vstudio.intelligence.manage') then
    raise exception 'insufficient privilege: vstudio.intelligence.manage required'
      using errcode = 'insufficient_privilege';
  end if;

  select * into v_def from vstudio.portfolios where key = p_key;
  if not found then
    raise exception 'unknown portfolio: %', p_key using errcode = 'no_data_found';
  end if;
  if v_def.rank_by = 'pain' then
    raise exception 'the pain portfolio ranks clusters, not repositories — use vstudio.build_pain_portfolio()'
      using errcode = 'feature_not_supported';
  end if;

  select count(*) into v_corpus from vstudio.opportunities;
  select count(*) into v_eligible from vstudio.portfolio_candidates(p_key);

  insert into vstudio.portfolio_snapshots
    (portfolio_key, scoring_version, corpus_size, eligible_count, member_count, method, is_current)
  values (p_key, v_version, v_corpus, v_eligible, 0,
    'Ranked on ' || v_def.rank_by || ' over ' || v_eligible || ' eligible of ' || v_corpus ||
    ' corpus records, scoring version ' || v_version ||
    '. Eligibility: ' || case when p_key = 'outside-core'
      then 'no core-domain match reached ' || ${QUALIFICATION_THRESHOLD} || ' and popularity is measured'
      else 'domain match >= ' || ${QUALIFICATION_THRESHOLD} end || '.',
    false)
  returning id into v_snapshot;

  -- The ranked selection. Ordering is fully deterministic: the ranking score,
  -- then the OTHER score as tiebreak, then the id. Without the final key a
  -- rebuild could reshuffle equal-scoring rows and the list would look
  -- unstable for no reason.
  insert into vstudio.portfolio_members (
    snapshot_id, opportunity_id, rank,
    popularity_score, popularity_status, suitability_score, suitability_status, rising_score,
    ranking_basis, ranking_score, qualification
  )
  select
    v_snapshot, e.opportunity_id, e.rn,
    e.popularity_score, e.popularity_status, e.suitability_score, e.suitability_status, e.rising_score,
    v_def.rank_by, e.rank_score,
    jsonb_build_object(
      'domain_value', round(e.domain_value, 4),
      'best_core_value', round(coalesce(e.best_core_value, 0), 4),
      'matched_terms', coalesce(e.matched_terms, '[]'::jsonb),
      'category', e.category,
      'threshold', ${QUALIFICATION_THRESHOLD},
      'basis', case when p_key = 'outside-core'
        then 'no core-domain match reached the threshold; ranked on measured popularity'
        else 'domain match ' || round(e.domain_value, 2) || ' from category and vocabulary evidence' end
    )
  from (
    select c.*, row_number() over (
      order by c.rank_score desc nulls last, c.tie_score desc nulls last, c.opportunity_id
    ) as rn
    from vstudio.portfolio_candidates(p_key) c
  ) e
  where e.rn <= v_def.target_size;

  get diagnostics v_members = row_count;

  update vstudio.portfolio_snapshots set member_count = v_members where id = v_snapshot;

  -- Flip current LAST, so a failed build never leaves the CEO looking at a
  -- half-written ranking.
  update vstudio.portfolio_snapshots set is_current = false
   where portfolio_key = p_key and is_current and id <> v_snapshot;
  update vstudio.portfolio_snapshots set is_current = true where id = v_snapshot;

  return v_snapshot;
end;
$fn$;
revoke all on function vstudio.build_portfolio(text) from public, anon;
grant execute on function vstudio.build_portfolio(text) to authenticated;
comment on function vstudio.build_portfolio(text) is
  'Rebuild one Top-100 as a new immutable snapshot. Selects and ranks over vstudio.opportunities without modifying it. Records corpus_size, eligible_count and member_count so a short list is never presented as a full hundred.';
`;

writeFileSync(OUT, sql);
console.log(JSON.stringify({ out: OUT, bytes: sql.length, portfolios: CORE_PORTFOLIOS.map((p) => p.key) }, null, 1));
