/**
 * Generate the Level-1 triage SQL from the source-controlled scoring module.
 *
 * WHY GENERATE IT. The corpus is 62,250 rows and this container cannot reach
 * the database directly, so the scoring has to run server-side in SQL. But the
 * weights, term lists and thresholds must stay reviewable and testable, which
 * means TypeScript. Maintaining both by hand guarantees they drift, and a
 * ranking computed by a formula nobody reviewed is exactly the opaque score
 * the brief forbids.
 *
 * So there is one source of truth — packages/venture-studio/src/scoring.ts and
 * ./portfolios.ts — and this script compiles it to SQL. The vitest suite tests
 * the TypeScript; the generated SQL is arithmetic over the same constants.
 *
 * Usage: tsx scripts/build-scoring-sql.mts [--out FILE]
 */
import { writeFileSync } from "node:fs";
import {
  SCORING_VERSION,
  POPULARITY_WEIGHTS,
  POPULARITY_CEILINGS,
  SUITABILITY_WEIGHTS,
  RECENCY_HORIZON_DAYS,
  BUILDABILITY_PEAK_STARS,
  PERMISSIVE_LICENCES,
  COPYLEFT_LICENCES,
  HLG_STACK,
  MONETIZABLE_TOPICS,
} from "../packages/venture-studio/src/scoring.ts";
import {
  CORE_PORTFOLIOS,
  MIN_CORE_TERMS_WITHOUT_CATEGORY,
  QUALIFICATION_THRESHOLD,
} from "../packages/venture-studio/src/portfolios.ts";

const outIdx = process.argv.indexOf("--out");
const OUT =
  outIdx > -1
    ? String(process.argv[outIdx + 1])
    : "supabase/migrations/20260820140000_hlbos_0034_vstudio_level1_triage.sql";

/** SQL string literal. */
const q = (v: string): string => `'${v.replace(/'/g, "''")}'`;
const arr = (xs: readonly string[]): string => `array[${xs.map(q).join(",")}]`;

/**
 * A regex alternation matching any of the terms on word boundaries.
 * Longest first, because Postgres alternation is leftmost-preferring: with
 * "route" before "route optimization" the longer phrase would never be seen.
 */
function alternation(terms: readonly string[]): string {
  const escaped = [...terms]
    .sort((a, b) => b.length - a.length)
    .map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  return `\\m(${escaped.join("|")})\\M`;
}

/** clamp01 in SQL. */
const c01 = (e: string): string => `greatest(0::numeric, least(1::numeric, ${e}))`;
/** logNormalize in SQL. */
const logN = (col: string, ceiling: number): string =>
  `${c01(`log(10::numeric, (coalesce(${col},0))::numeric + 1) / log(10::numeric, ${ceiling}::numeric + 1)`)}`;

const P = POPULARITY_WEIGHTS;
const S = SUITABILITY_WEIGHTS;

// --- Per-portfolio term matching --------------------------------------------
// Core and supporting vocabulary are captured SEPARATELY, because they carry
// different weight: core terms qualify a record on their own, supporting terms
// only strengthen a match that already exists. Collapsing them into one list
// is what put a media-server dashboard at the top of the Sports Top-100.
const matchColumns = CORE_PORTFOLIOS.map((p) => {
  const k = p.key.replace(/-/g, "_");
  return `
    (select coalesce(array_agg(distinct m[1]), '{}'::text[])
       from regexp_matches(b.haystack, ${q(alternation(p.coreTerms))}, 'g') m) as ${k}_core,
    (select coalesce(array_agg(distinct m[1]), '{}'::text[])
       from regexp_matches(b.haystack, ${q(alternation(p.supportingTerms))}, 'g') m) as ${k}_sup,
    (b.category = any(${arr(p.categories)})) as ${k}_cat`;
}).join(",");

const matchValues = CORE_PORTFOLIOS.map((p) => {
  const k = p.key.replace(/-/g, "_");
  const strength = `(least(4::numeric, coalesce(cardinality(m.${k}_core),0)::numeric + 0.5 * coalesce(cardinality(m.${k}_sup),0)::numeric) / 4)`;
  return `    case
      when m.${k}_cat then least(1::numeric, 0.6 + 0.4 * ${strength})
      when coalesce(cardinality(m.${k}_core),0) >= ${MIN_CORE_TERMS_WITHOUT_CATEGORY} then least(1::numeric, 0.35 + 0.65 * ${strength})
      else 0::numeric
    end as ${k}_value`;
}).join(",\n");

const bestCore = CORE_PORTFOLIOS.map((p) => `v.${p.key.replace(/-/g, "_")}_value`).join(
  ", ",
);
// A portfolio name is only reported when the match actually clears the
// qualification threshold. Without the guard, a record matching nothing at all
// would still be labelled "logistics" purely because greatest() of three zeroes
// equals the first of them — a made-up answer dressed as a computed one.
const bestCoreKey = CORE_PORTFOLIOS.map(
  (p) =>
    `when v.${p.key.replace(/-/g, "_")}_value = greatest(${bestCore}) then ${q(p.key)}`,
).join("\n              ");

const sql = `-- ===========================================================================
-- hlbos_0034_vstudio_level1_triage — the Level-1 scoring function
--
-- GENERATED FILE. Do not edit by hand.
-- Generated by scripts/build-scoring-sql.mts from
--   packages/venture-studio/src/scoring.ts
--   packages/venture-studio/src/portfolios.ts
-- Re-run the generator after changing either and commit the regenerated file;
-- the vitest suite proves the arithmetic, and this is that same arithmetic
-- expressed over 62,250 rows.
--
-- Scoring version: ${SCORING_VERSION}
--
-- WHY THIS IS A FUNCTION AND NOT A ONE-OFF SCRIPT
--
-- Scores must be RE-COMPUTABLE. Evidence changes: a repository gains stars,
-- goes quiet, gets archived. A ranking that can only be produced once, by
-- pasting a query somebody no longer has, is not reproducible — and the brief
-- requires that if the evidence changes, the rankings can change with it. So
-- the engine lives in the database as a callable control, source-controlled
-- here, and the Control Center can invoke it.
--
-- WHY IT TAKES A CATEGORY
--
-- The full corpus exceeds the statement timeout in one pass. The batch key is
-- the discovery CATEGORY, and that choice is not arbitrary: the popularity
-- score ranks each repository WITHIN its own category, so a category is
-- exactly one window partition. Batching this way produces byte-identical
-- results to a single-pass run. Any other batch key (id ranges, row limits)
-- would split a partition and silently change every percentile in it.
--
-- PURELY ADDITIVE, and read-only over the corpus: every write goes to
-- vstudio.opportunity_scores. Not one row of vstudio.opportunities is
-- modified, reduced or reordered by running this.
--
-- rollback: (manual, pre-approval only)
--   DROP FUNCTION IF EXISTS vstudio.score_level1(text);
--   DROP FUNCTION IF EXISTS vstudio.score_level1_categories();
--   DELETE FROM vstudio.opportunity_scores WHERE scoring_version = ${q(SCORING_VERSION)};
--
-- VERIFICATION (after apply): vstudio.score_level1_categories() lists every
--   category partition; calling vstudio.score_level1(k) for each returns the
--   number of rows scored, summing to the corpus size. pgTAP:
--   supabase/tests/34_vstudio_level1_triage.sql.
-- ===========================================================================

-- Every distinct category partition, NULL included, so a driver can enumerate
-- the work without guessing at it. NULL is a real partition: the 36
-- opportunities captured before discovery ran carry no category.
create or replace function vstudio.score_level1_categories()
returns table (category text, opportunities bigint)
language sql stable security definer set search_path = '' as $fn$
  select o.category, count(*)
  from vstudio.opportunities o
  group by o.category
  order by count(*) desc;
$fn$;
revoke all on function vstudio.score_level1_categories() from public, anon;
grant execute on function vstudio.score_level1_categories() to authenticated;

-- Score one category partition. Returns the number of rows scored.
create or replace function vstudio.score_level1(p_category text)
returns integer
language plpgsql volatile security definer set search_path = '' as $fn$
declare v_rows integer;
begin
  -- Running the analysis is a privilege distinct from reading its results.
  -- The gate lives in one place (migration 0039) so that every intelligence
  -- control shares it and so that it can actually be tested: it admits a
  -- direct maintenance connection, which has no request context to authorise
  -- against, and requires vstudio.intelligence.manage from everyone else.
  perform vstudio.assert_intelligence_manage();

insert into vstudio.opportunity_scores (
  opportunity_id, scoring_version, analysis_level,
  popularity_score, popularity_status, popularity_components,
  suitability_score, suitability_status, suitability_components,
  evidence, method, computed_at
)
with base as (
  select
    o.id, o.category, o.search_pattern, o.stars, o.forks, o.open_issues,
    o.pushed_at, o.archived, o.topics, o.license, o.language,
    -- One lowercased haystack per row: name, description and declared topics.
    -- Separators are flattened to spaces so "route/planner" and "route_planner"
    -- match the same vocabulary a human would read them as.
    regexp_replace(
      lower(coalesce(o.title,'') || ' ' || coalesce(o.summary,'') || ' ' ||
            array_to_string(coalesce(o.topics,'{}'::text[]), ' ')),
      '[_/\\\\]+', ' ', 'g') as haystack,
    (select count(*) from unnest(coalesce(o.topics,'{}'::text[])) t
      where lower(t) = any(${arr(MONETIZABLE_TOPICS)})) as money_hits
  from vstudio.opportunities o
  -- IS NOT DISTINCT FROM, so the NULL-category partition is selectable too.
  where o.category is not distinct from p_category
),
ranked as (
  select b.*,
    -- Rank WITHIN the discovery category. cume_dist rather than percent_rank so
    -- the only row in a small category scores 1 instead of 0 — being the whole
    -- of a category is not the same as being the bottom of one.
    -- Cast to numeric: cume_dist() returns double precision, and letting that
    -- leak into the score arithmetic silently promotes every downstream
    -- expression to floating point.
    case when b.stars is null then null
         else cume_dist() over (partition by b.category order by b.stars)::numeric end as stars_pct,
    case when b.forks is null then null
         else cume_dist() over (partition by b.category order by b.forks)::numeric end as forks_pct
  from base b
),
matched as (
  select b.*,${matchColumns}
  from ranked b
),
valued as (
  select m.*,
${matchValues}
  from matched m
),
computed as (
  select v.*,
    -- --- popularity components (each 0-1) ---
    ${c01(`0.5 * ${logN("v.stars", POPULARITY_CEILINGS.stars)} + 0.5 * coalesce(v.stars_pct, ${logN("v.stars", POPULARITY_CEILINGS.stars)})`)} as p_stars,
    ${c01(`0.5 * ${logN("v.forks", POPULARITY_CEILINGS.forks)} + 0.5 * coalesce(v.forks_pct, ${logN("v.forks", POPULARITY_CEILINGS.forks)})`)} as p_forks,
    ${logN("v.open_issues", POPULARITY_CEILINGS.openIssues)} as p_issues,
    case when v.pushed_at is null then 0::numeric
         else ${c01(`1 - (greatest(0, extract(epoch from (now() - v.pushed_at)) / 86400))::numeric / ${RECENCY_HORIZON_DAYS}`)} end as p_recency,
    ${c01(`coalesce(cardinality(v.topics),0)::numeric / ${POPULARITY_CEILINGS.topics}`)} as p_topics,

    -- --- suitability components (each 0-1) ---
    greatest(${bestCore}) as s_domain,
    case when v.language is null then 0.30::numeric
         when v.language = any(${arr(HLG_STACK)}) then 1::numeric
         else 0.35::numeric end as s_stack,
    case when v.license is null or v.license = 'NOASSERTION' then 0.25::numeric
         when v.license = any(${arr(PERMISSIVE_LICENCES)}) then 1::numeric
         when v.license = any(${arr(COPYLEFT_LICENCES)}) then 0.30::numeric
         else 0.50::numeric end as s_licence,
    case when v.stars is null then 0.30::numeric
         else ${c01(`1 - 0.7 * (abs(log(10::numeric, v.stars::numeric + 1) - log(10::numeric, ${BUILDABILITY_PEAK_STARS}::numeric + 1)) / log(10::numeric, ${BUILDABILITY_PEAK_STARS}::numeric + 1))`)} end as s_build,
    case when v.archived then ${c01(`0.6 + 0.4 * ${logN("v.stars", 20000)}`)}
         when v.search_pattern = 'ABANDONED' then ${c01(`0.5 + 0.5 * ${logN("v.stars", 20000)}`)}
         when v.search_pattern = 'UNDERDEVELOPED' then ${c01(`0.35 + 0.5 * ${logN("v.stars", 20000)}`)}
         when v.search_pattern = 'ALTERNATIVES' then ${c01(`0.3 + 0.4 * ${logN("v.stars", 20000)}`)}
         else ${c01(`0.15 * (1 + ${logN("v.stars", 20000)})`)} end as s_maintenance,
    ${c01(`v.money_hits::numeric / 4 + case when v.search_pattern in ('SELF-HOSTED','ALTERNATIVES') then 0.3 else 0 end`)} as s_money,
    case when greatest(${bestCore}) < ${QUALIFICATION_THRESHOLD} then null
         else case ${bestCoreKey}
              else null end
    end as best_core,
    greatest(${bestCore}) as best_core_value,
    (v.stars is not null or v.forks is not null or v.open_issues is not null) as measurable
  from valued v
)
select
  c.id,
  ${q(SCORING_VERSION)},
  1,
  -- POPULARITY. Null where no repository metric exists at all: a research note
  -- captured before discovery ran is not an unpopular repository, and scoring
  -- it zero would rank it below genuinely dead projects on evidence we never had.
  case when c.measurable then round(
    (c.p_stars * ${P.stars} + c.p_forks * ${P.forks} + c.p_issues * ${P.issueActivity}
     + c.p_recency * ${P.recency} + c.p_topics * ${P.topicBreadth}) / 100 * 100)::int
  end,
  case when c.measurable then 'measured'::vstudio.metric_status else 'unknown'::vstudio.metric_status end,
  case when c.measurable then jsonb_build_array(
    jsonb_build_object('c','stars','v',round(c.p_stars,4),'w',${P.stars}),
    jsonb_build_object('c','forks','v',round(c.p_forks,4),'w',${P.forks}),
    jsonb_build_object('c','issue_activity','v',round(c.p_issues,4),'w',${P.issueActivity}),
    jsonb_build_object('c','recency','v',round(c.p_recency,4),'w',${P.recency}),
    jsonb_build_object('c','topic_breadth','v',round(c.p_topics,4),'w',${P.topicBreadth})
  ) else '[]'::jsonb end,
  -- HLG SUITABILITY. Always ESTIMATED — a structured inference from observable
  -- properties, never a measurement. The CHECK on the table makes the honest
  -- label the only storable one.
  round((c.s_domain * ${S.domainOverlap} + c.s_stack * ${S.stackReuse}
       + c.s_licence * ${S.licenceCommercial} + c.s_build * ${S.buildability}
       + c.s_maintenance * ${S.maintenanceOpening} + c.s_money * ${S.monetizationSurface}) / 100 * 100)::int,
  'estimated'::vstudio.metric_status,
  jsonb_build_array(
    jsonb_build_object('c','domain_overlap','v',round(c.s_domain,4),'w',${S.domainOverlap}),
    jsonb_build_object('c','stack_reuse','v',round(c.s_stack,4),'w',${S.stackReuse}),
    jsonb_build_object('c','licence_commercial','v',round(c.s_licence,4),'w',${S.licenceCommercial}),
    jsonb_build_object('c','buildability','v',round(c.s_build,4),'w',${S.buildability}),
    jsonb_build_object('c','maintenance_opening','v',round(c.s_maintenance,4),'w',${S.maintenanceOpening}),
    jsonb_build_object('c','monetization_surface','v',round(c.s_money,4),'w',${S.monetizationSurface})
  ),
  -- Evidence: only what is NOT already on the corpus row. Stars, forks, licence
  -- and the rest stay where they are; duplicating them would create a second
  -- copy that can disagree with the first.
  jsonb_build_object(
    'stars_pct', round(coalesce(c.stars_pct,0),4),
    'forks_pct', round(coalesce(c.forks_pct,0),4),
    'best_core', c.best_core,
    'best_core_value', round(c.best_core_value,4),
    'qualification_threshold', ${QUALIFICATION_THRESHOLD},
    'matched', jsonb_build_object(
${CORE_PORTFOLIOS.map((p) => `      ${q(p.key)}, jsonb_build_object('core', to_jsonb(c.${p.key.replace(/-/g, "_")}_core), 'sup', to_jsonb(c.${p.key.replace(/-/g, "_")}_sup))`).join(",\n")}
    )
  ),
  'Level-1 deterministic triage, generated from packages/venture-studio/src/scoring.ts (${SCORING_VERSION}). Popularity measured from repository metrics; HLG suitability estimated from domain vocabulary, stack, licence, scale, discovery pattern and commercial-shape topics. No external research, no model, no invented figures.',
  now()
from computed c
on conflict (opportunity_id, scoring_version) do update set
  analysis_level         = excluded.analysis_level,
  popularity_score       = excluded.popularity_score,
  popularity_status      = excluded.popularity_status,
  popularity_components  = excluded.popularity_components,
  suitability_score      = excluded.suitability_score,
  suitability_status     = excluded.suitability_status,
  suitability_components = excluded.suitability_components,
  evidence               = excluded.evidence,
  method                 = excluded.method,
  computed_at            = excluded.computed_at;

  get diagnostics v_rows = row_count;
  return v_rows;
end;
$fn$;
revoke all on function vstudio.score_level1(text) from public, anon;
grant execute on function vstudio.score_level1(text) to authenticated;

comment on function vstudio.score_level1(text) is
  'Level-1 deterministic triage for one discovery-category partition. Generated from packages/venture-studio/src/scoring.ts (${SCORING_VERSION}). Read-only over vstudio.opportunities; writes only to vstudio.opportunity_scores.';
`;

writeFileSync(OUT, sql);
console.log(
  JSON.stringify(
    {
      out: OUT,
      scoringVersion: SCORING_VERSION,
      bytes: sql.length,
      portfolios: CORE_PORTFOLIOS.map((p) => ({
        key: p.key,
        core: p.coreTerms.length,
        supporting: p.supportingTerms.length,
        categories: p.categories.length,
      })),
    },
    null,
    1,
  ),
);
