/**
 * Side-effect CSS imports.
 *
 * `next-env.d.ts` declares this, but it is generated by `next build` and
 * gitignored, so a clean checkout running `pnpm typecheck` before any build
 * would fail on `import "./globals.css"`. Declaring it here keeps the
 * typecheck honest on a cold clone.
 */
declare module "*.css";
