/**
 * The columns this app selects, per table.
 *
 * Extracted from data.ts so `schema.test.ts` can assert them against
 * supabase/migrations/…_0048_football_filmstudy.sql without importing a
 * server-only module.
 *
 * This is the guard that keeps the hand-written row types in lib/types.ts
 * honest. Those types cannot be generated here — generating them needs a live
 * Supabase project, and this app must typecheck and build without one — so a
 * renamed or dropped column would otherwise typecheck perfectly and fail at
 * runtime in front of a coach.
 */

export const SELECTED_COLUMNS = {
  teams: [
    "id",
    "tenant_id",
    "name",
    "level",
    "mascot",
    "grade_scale",
    "athletes_see_grades",
    "guardian_access",
    "guardians_see_grades",
    "is_demo",
  ],
  team_members: ["football_role", "team_id", "user_id"],
  player_links: ["player_id", "team_id", "user_id"],
  seasons: ["id", "year", "label", "is_current", "team_id"],
  players: [
    "id",
    "jersey_number",
    "first_name",
    "last_name",
    "position",
    "unit",
    "class_year",
    "height_inches",
    "weight_pounds",
    "active",
    "team_id",
  ],
  opponents: ["id", "name", "mascot", "team_id"],
  games: [
    "id",
    "opponent_id",
    "kickoff_at",
    "venue",
    "location",
    "week",
    "team_score",
    "opponent_score",
    "notes",
    "team_id",
  ],
  film_assets: [
    "id",
    "game_id",
    "title",
    "film_kind",
    "unit",
    "status",
    "bucket",
    "object_path",
    "original_filename",
    "size_bytes",
    "duration_seconds",
    "recorded_on",
    "notes",
    "athlete_visible",
    "created_at",
    "team_id",
  ],
  plays: [
    "id",
    "film_asset_id",
    "game_id",
    "play_number",
    "start_seconds",
    "end_seconds",
    "snap_seconds",
    "quarter",
    "clock",
    "down",
    "distance",
    "yard_line",
    "hash",
    "possession",
    "personnel",
    "formation",
    "strength",
    "motion",
    "play_call",
    "family",
    "concept",
    "direction",
    "defensive_front",
    "box_count",
    "coverage",
    "pressure",
    "result",
    "yards",
    "touchdown",
    "first_down",
    "turnover",
    "penalty",
    "explosive",
    "red_zone",
    "third_down",
    "goal_line",
    "team_id",
  ],
  predictions: [
    "id",
    "play_id",
    "prediction_type",
    "predicted_value",
    "confidence",
    "model",
    "model_version",
    "state",
  ],
  play_participation: ["id", "play_id", "player_id", "unit", "position", "assignment"],
  grade_categories: ["id", "key", "label", "sort_order", "active", "team_id"],
  player_grades: [
    "id",
    "play_id",
    "player_id",
    "category_key",
    "symbol",
    "numeric_value",
  ],
  player_notes: [
    "id",
    "player_id",
    "play_id",
    "timestamp_seconds",
    "body",
    "visible_to_athlete",
    "source",
    "created_at",
  ],
  clips: [
    "id",
    "film_asset_id",
    "play_id",
    "title",
    "caption",
    "start_seconds",
    "end_seconds",
    "playback_rate",
    "created_at",
    "team_id",
  ],
  playlists: [
    "id",
    "name",
    "description",
    "generated_by",
    "shared_with_athletes",
    "created_at",
    "team_id",
  ],
  playlist_items: ["id", "playlist_id", "play_id", "clip_id", "position", "note"],
  film_assignments: [
    "id",
    "player_id",
    "assignment_kind",
    "message",
    "due_on",
    "status",
    "created_at",
    "team_id",
  ],
  assignment_items: ["id", "assignment_id", "play_id", "clip_id", "position"],
  // `as const satisfies` rather than a Record annotation: the literal keys are
  // what let data.ts index this map under `noUncheckedIndexedAccess` without a
  // non-null assertion, and a typo in a table name then fails to compile.
} as const satisfies Record<string, readonly string[]>;

/** RPCs the app calls, with the argument names it passes. */
export const CALLED_RPCS = {
  create_team: ["p_tenant", "p_name", "p_level", "p_mascot"],
  seed_demo_program: ["p_tenant"],
  remove_demo_program: ["p_tenant"],
  update_team_settings: [
    "p_team",
    "p_grade_scale",
    "p_athletes_see_grades",
    "p_guardian_access",
    "p_guardians_see_grades",
  ],
  upsert_season: ["p_team", "p_year", "p_label", "p_is_current"],
  upsert_player: [
    "p_team",
    "p_first_name",
    "p_last_name",
    "p_jersey_number",
    "p_position",
    "p_unit",
    "p_class_year",
    "p_height_inches",
    "p_weight_pounds",
    "p_player",
  ],
  upsert_opponent: ["p_team", "p_name", "p_mascot"],
  upsert_game: [
    "p_team",
    "p_opponent",
    "p_season",
    "p_kickoff_at",
    "p_venue",
    "p_location",
    "p_week",
    "p_team_score",
    "p_opponent_score",
    "p_notes",
    "p_game",
  ],
  register_film: [
    "p_team",
    "p_title",
    "p_kind",
    "p_original_filename",
    "p_mime",
    "p_size_bytes",
    "p_game",
    "p_season",
    "p_unit",
    "p_recorded_on",
    "p_notes",
    "p_athlete_visible",
  ],
  confirm_film_upload: ["p_film", "p_size_bytes", "p_duration_seconds"],
  set_film_visibility: ["p_film", "p_athlete_visible"],
  create_play: ["p_film", "p_start_seconds", "p_end_seconds", "p_snap_seconds"],
  delete_play: ["p_play"],
  set_play_window: ["p_play", "p_start_seconds", "p_end_seconds", "p_snap_seconds"],
  tag_play: [
    "p_play",
    "p_quarter",
    "p_clock",
    "p_down",
    "p_distance",
    "p_yard_line",
    "p_hash",
    "p_possession",
    "p_personnel",
    "p_formation",
    "p_strength",
    "p_motion",
    "p_play_call",
    "p_family",
    "p_concept",
    "p_direction",
    "p_defensive_front",
    "p_box_count",
    "p_coverage",
    "p_pressure",
    "p_result",
    "p_yards",
    "p_touchdown",
    "p_first_down",
    "p_turnover",
    "p_penalty",
    "p_explosive",
    "p_red_zone",
    "p_third_down",
    "p_goal_line",
    "p_confirmation_kind",
  ],
  resolve_prediction: ["p_prediction", "p_state", "p_corrected_value"],
  set_participation: ["p_play", "p_player", "p_unit", "p_position", "p_assignment"],
  remove_participation: ["p_play", "p_player"],
  set_grade: ["p_play", "p_player", "p_category", "p_symbol", "p_numeric"],
  add_note: [
    "p_player",
    "p_body",
    "p_play",
    "p_timestamp_seconds",
    "p_visible_to_athlete",
    "p_source",
  ],
  create_clip: [
    "p_film",
    "p_title",
    "p_start_seconds",
    "p_end_seconds",
    "p_play",
    "p_caption",
    "p_playback_rate",
  ],
  create_playlist: ["p_team", "p_name", "p_description", "p_shared_with_athletes"],
  add_playlist_item: ["p_playlist", "p_play", "p_clip", "p_note"],
  remove_playlist_item: ["p_item"],
  create_assignment: ["p_player", "p_kind", "p_message", "p_due_on"],
  add_assignment_item: ["p_assignment", "p_play", "p_clip"],
  record_assignment_progress: ["p_assignment", "p_status", "p_comment"],
} as const satisfies Record<string, readonly string[]>;
