#!/usr/bin/env node
/**
 * Apply store/release.json to every place a version number is stated.
 *
 * Three files carry the version -- the web build's env, Android's Gradle
 * config, and the Xcode project -- and keeping them in step by hand is how a
 * user ends up reporting a bug against a build number nobody can find.
 *
 * Apple and Google both reject an upload whose build number has not increased,
 * including a re-upload after a rejection, so the build is bumped in one place
 * and propagated from there.
 *
 *   node scripts/set-release.mjs            # apply release.json
 *   node scripts/set-release.mjs --bump     # increment the build first
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RELEASE = path.join(APP, "store/release.json");

const release = JSON.parse(readFileSync(RELEASE, "utf8"));
if (process.argv.includes("--bump")) {
  release.build = Number(release.build) + 1;
  writeFileSync(RELEASE, `${JSON.stringify(release, null, 2)}\n`);
}

const { version, build } = release;
if (!/^\d+\.\d+\.\d+$/.test(String(version))) {
  console.error(
    `store/release.json: version must be MAJOR.MINOR.PATCH, got ${version}`,
  );
  process.exit(1);
}
if (!Number.isInteger(build) || build < 1) {
  console.error(`store/release.json: build must be a positive integer, got ${build}`);
  process.exit(1);
}

const touched = [];

// A generated TypeScript module rather than a .env file. The repository
// gitignores every .env by policy -- correctly, since that is where secrets
// live -- and a version number that only exists in an ignored file would be
// "0.1.0 (dev)" in every build anyone else made. This holds no secret, so it
// is committed and the build always states the truth about itself.
const release_ts = path.join(APP, "src/lib/release.ts");
writeFileSync(
  release_ts,
  [
    "// GENERATED by scripts/set-release.mjs from store/release.json.",
    "// Do not edit by hand -- edit store/release.json and re-run the script.",
    "",
    `export const APP_VERSION = ${JSON.stringify(version)};`,
    `export const BUILD_NUMBER = ${JSON.stringify(String(build))};`,
    "",
  ].join("\n"),
);
touched.push("src/lib/release.ts");

const gradle = path.join(APP, "android/app/build.gradle");
if (existsSync(gradle)) {
  const next = readFileSync(gradle, "utf8")
    .replace(/versionCode\s+\d+/, `versionCode ${build}`)
    .replace(/versionName\s+"[^"]*"/, `versionName "${version}"`);
  writeFileSync(gradle, next);
  touched.push("android/app/build.gradle");
}

const pbxproj = path.join(APP, "ios/App/App.xcodeproj/project.pbxproj");
if (existsSync(pbxproj)) {
  const next = readFileSync(pbxproj, "utf8")
    .replace(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${build};`)
    .replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${version};`);
  writeFileSync(pbxproj, next);
  touched.push("ios/App/App.xcodeproj/project.pbxproj");
}

console.log(`PlayTime Tracker ${version} (${build})`);
for (const f of touched) console.log(`  updated ${f}`);
if (touched.length < 3) {
  console.log(
    "  (a native project is missing; run `npx cap add ios` / `npx cap add android`)",
  );
}
